/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OrgUnitLevel } from '../model/orgUnitLevel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class OrgUnitLevelResourceService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createOrgUnitLevel
     * 
     * @param OrgUnitLevel orgUnitLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createOrgUnitLevelUsingPOST(OrgUnitLevel: OrgUnitLevel, observe?: 'body', reportProgress?: boolean): Observable<OrgUnitLevel>;
    public createOrgUnitLevelUsingPOST(OrgUnitLevel: OrgUnitLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OrgUnitLevel>>;
    public createOrgUnitLevelUsingPOST(OrgUnitLevel: OrgUnitLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OrgUnitLevel>>;
    public createOrgUnitLevelUsingPOST(OrgUnitLevel: OrgUnitLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (OrgUnitLevel === null || OrgUnitLevel === undefined) {
            throw new Error('Required parameter OrgUnitLevel was null or undefined when calling createOrgUnitLevelUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<OrgUnitLevel>(`${this.basePath}/api/org-unit-levels`,
            OrgUnitLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteOrgUnitLevel
     * 
     * @param Id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteOrgUnitLevelUsingDELETE(Id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteOrgUnitLevelUsingDELETE(Id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteOrgUnitLevelUsingDELETE(Id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteOrgUnitLevelUsingDELETE(Id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Id === null || Id === undefined) {
            throw new Error('Required parameter Id was null or undefined when calling deleteOrgUnitLevelUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/org-unit-levels/${encodeURIComponent(String(Id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllOrgUnitLevels
     * 
     * @param CodeContains 
     * @param CodeEquals 
     * @param CodeIn 
     * @param CodeSpecified 
     * @param CreatedEquals 
     * @param CreatedGreaterOrEqualThan 
     * @param CreatedGreaterThan 
     * @param CreatedIn0EpochSecond 
     * @param CreatedIn0Nano 
     * @param CreatedLessOrEqualThan 
     * @param CreatedLessThan 
     * @param CreatedSpecified 
     * @param IdEquals 
     * @param IdGreaterOrEqualThan 
     * @param IdGreaterThan 
     * @param IdIn 
     * @param IdLessOrEqualThan 
     * @param IdLessThan 
     * @param IdSpecified 
     * @param LastUpdateEquals 
     * @param LastUpdateGreaterOrEqualThan 
     * @param LastUpdateGreaterThan 
     * @param LastUpdateIn0EpochSecond 
     * @param LastUpdateIn0Nano 
     * @param LastUpdateLessOrEqualThan 
     * @param LastUpdateLessThan 
     * @param LastUpdateSpecified 
     * @param LevelEquals 
     * @param LevelGreaterOrEqualThan 
     * @param LevelGreaterThan 
     * @param LevelIn 
     * @param LevelLessOrEqualThan 
     * @param LevelLessThan 
     * @param LevelSpecified 
     * @param NameContains 
     * @param NameEquals 
     * @param NameIn 
     * @param NameSpecified 
     * @param Offset 
     * @param Page Page number of the requested page
     * @param PageNumber 
     * @param PageSize 
     * @param Paged 
     * @param Size Size of a page
     * @param Sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param SortSorted 
     * @param SortUnsorted 
     * @param Unpaged 
     * @param UuidContains 
     * @param UuidEquals 
     * @param UuidIn 
     * @param UuidSpecified 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllOrgUnitLevelsUsingGET(CodeContains?: string, CodeEquals?: string, CodeIn?: Array<string>, CodeSpecified?: boolean, CreatedEquals?: Date, CreatedGreaterOrEqualThan?: Date, CreatedGreaterThan?: Date, CreatedIn0EpochSecond?: number, CreatedIn0Nano?: number, CreatedLessOrEqualThan?: Date, CreatedLessThan?: Date, CreatedSpecified?: boolean, IdEquals?: number, IdGreaterOrEqualThan?: number, IdGreaterThan?: number, IdIn?: Array<number>, IdLessOrEqualThan?: number, IdLessThan?: number, IdSpecified?: boolean, LastUpdateEquals?: Date, LastUpdateGreaterOrEqualThan?: Date, LastUpdateGreaterThan?: Date, LastUpdateIn0EpochSecond?: number, LastUpdateIn0Nano?: number, LastUpdateLessOrEqualThan?: Date, LastUpdateLessThan?: Date, LastUpdateSpecified?: boolean, LevelEquals?: number, LevelGreaterOrEqualThan?: number, LevelGreaterThan?: number, LevelIn?: Array<number>, LevelLessOrEqualThan?: number, LevelLessThan?: number, LevelSpecified?: boolean, NameContains?: string, NameEquals?: string, NameIn?: Array<string>, NameSpecified?: boolean, Offset?: number, Page?: number, PageNumber?: number, PageSize?: number, Paged?: boolean, Size?: number, Sort?: Array<string>, SortSorted?: boolean, SortUnsorted?: boolean, Unpaged?: boolean, UuidContains?: string, UuidEquals?: string, UuidIn?: Array<string>, UuidSpecified?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<OrgUnitLevel>>;
    public getAllOrgUnitLevelsUsingGET(CodeContains?: string, CodeEquals?: string, CodeIn?: Array<string>, CodeSpecified?: boolean, CreatedEquals?: Date, CreatedGreaterOrEqualThan?: Date, CreatedGreaterThan?: Date, CreatedIn0EpochSecond?: number, CreatedIn0Nano?: number, CreatedLessOrEqualThan?: Date, CreatedLessThan?: Date, CreatedSpecified?: boolean, IdEquals?: number, IdGreaterOrEqualThan?: number, IdGreaterThan?: number, IdIn?: Array<number>, IdLessOrEqualThan?: number, IdLessThan?: number, IdSpecified?: boolean, LastUpdateEquals?: Date, LastUpdateGreaterOrEqualThan?: Date, LastUpdateGreaterThan?: Date, LastUpdateIn0EpochSecond?: number, LastUpdateIn0Nano?: number, LastUpdateLessOrEqualThan?: Date, LastUpdateLessThan?: Date, LastUpdateSpecified?: boolean, LevelEquals?: number, LevelGreaterOrEqualThan?: number, LevelGreaterThan?: number, LevelIn?: Array<number>, LevelLessOrEqualThan?: number, LevelLessThan?: number, LevelSpecified?: boolean, NameContains?: string, NameEquals?: string, NameIn?: Array<string>, NameSpecified?: boolean, Offset?: number, Page?: number, PageNumber?: number, PageSize?: number, Paged?: boolean, Size?: number, Sort?: Array<string>, SortSorted?: boolean, SortUnsorted?: boolean, Unpaged?: boolean, UuidContains?: string, UuidEquals?: string, UuidIn?: Array<string>, UuidSpecified?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OrgUnitLevel>>>;
    public getAllOrgUnitLevelsUsingGET(CodeContains?: string, CodeEquals?: string, CodeIn?: Array<string>, CodeSpecified?: boolean, CreatedEquals?: Date, CreatedGreaterOrEqualThan?: Date, CreatedGreaterThan?: Date, CreatedIn0EpochSecond?: number, CreatedIn0Nano?: number, CreatedLessOrEqualThan?: Date, CreatedLessThan?: Date, CreatedSpecified?: boolean, IdEquals?: number, IdGreaterOrEqualThan?: number, IdGreaterThan?: number, IdIn?: Array<number>, IdLessOrEqualThan?: number, IdLessThan?: number, IdSpecified?: boolean, LastUpdateEquals?: Date, LastUpdateGreaterOrEqualThan?: Date, LastUpdateGreaterThan?: Date, LastUpdateIn0EpochSecond?: number, LastUpdateIn0Nano?: number, LastUpdateLessOrEqualThan?: Date, LastUpdateLessThan?: Date, LastUpdateSpecified?: boolean, LevelEquals?: number, LevelGreaterOrEqualThan?: number, LevelGreaterThan?: number, LevelIn?: Array<number>, LevelLessOrEqualThan?: number, LevelLessThan?: number, LevelSpecified?: boolean, NameContains?: string, NameEquals?: string, NameIn?: Array<string>, NameSpecified?: boolean, Offset?: number, Page?: number, PageNumber?: number, PageSize?: number, Paged?: boolean, Size?: number, Sort?: Array<string>, SortSorted?: boolean, SortUnsorted?: boolean, Unpaged?: boolean, UuidContains?: string, UuidEquals?: string, UuidIn?: Array<string>, UuidSpecified?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OrgUnitLevel>>>;
    public getAllOrgUnitLevelsUsingGET(CodeContains?: string, CodeEquals?: string, CodeIn?: Array<string>, CodeSpecified?: boolean, CreatedEquals?: Date, CreatedGreaterOrEqualThan?: Date, CreatedGreaterThan?: Date, CreatedIn0EpochSecond?: number, CreatedIn0Nano?: number, CreatedLessOrEqualThan?: Date, CreatedLessThan?: Date, CreatedSpecified?: boolean, IdEquals?: number, IdGreaterOrEqualThan?: number, IdGreaterThan?: number, IdIn?: Array<number>, IdLessOrEqualThan?: number, IdLessThan?: number, IdSpecified?: boolean, LastUpdateEquals?: Date, LastUpdateGreaterOrEqualThan?: Date, LastUpdateGreaterThan?: Date, LastUpdateIn0EpochSecond?: number, LastUpdateIn0Nano?: number, LastUpdateLessOrEqualThan?: Date, LastUpdateLessThan?: Date, LastUpdateSpecified?: boolean, LevelEquals?: number, LevelGreaterOrEqualThan?: number, LevelGreaterThan?: number, LevelIn?: Array<number>, LevelLessOrEqualThan?: number, LevelLessThan?: number, LevelSpecified?: boolean, NameContains?: string, NameEquals?: string, NameIn?: Array<string>, NameSpecified?: boolean, Offset?: number, Page?: number, PageNumber?: number, PageSize?: number, Paged?: boolean, Size?: number, Sort?: Array<string>, SortSorted?: boolean, SortUnsorted?: boolean, Unpaged?: boolean, UuidContains?: string, UuidEquals?: string, UuidIn?: Array<string>, UuidSpecified?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





















































        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (CodeContains !== undefined && CodeContains !== null) {
            queryParameters = queryParameters.set('code.contains', <any>CodeContains);
        }
        if (CodeEquals !== undefined && CodeEquals !== null) {
            queryParameters = queryParameters.set('code.equals', <any>CodeEquals);
        }
        if (CodeIn) {
            CodeIn.forEach((element) => {
                queryParameters = queryParameters.append('code.in', <any>element);
            })
        }
        if (CodeSpecified !== undefined && CodeSpecified !== null) {
            queryParameters = queryParameters.set('code.specified', <any>CodeSpecified);
        }
        if (CreatedEquals !== undefined && CreatedEquals !== null) {
            queryParameters = queryParameters.set('created.equals', <any>CreatedEquals.toISOString());
        }
        if (CreatedGreaterOrEqualThan !== undefined && CreatedGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('created.greaterOrEqualThan', <any>CreatedGreaterOrEqualThan.toISOString());
        }
        if (CreatedGreaterThan !== undefined && CreatedGreaterThan !== null) {
            queryParameters = queryParameters.set('created.greaterThan', <any>CreatedGreaterThan.toISOString());
        }
        if (CreatedIn0EpochSecond !== undefined && CreatedIn0EpochSecond !== null) {
            queryParameters = queryParameters.set('created.in[0].epochSecond', <any>CreatedIn0EpochSecond);
        }
        if (CreatedIn0Nano !== undefined && CreatedIn0Nano !== null) {
            queryParameters = queryParameters.set('created.in[0].nano', <any>CreatedIn0Nano);
        }
        if (CreatedLessOrEqualThan !== undefined && CreatedLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('created.lessOrEqualThan', <any>CreatedLessOrEqualThan.toISOString());
        }
        if (CreatedLessThan !== undefined && CreatedLessThan !== null) {
            queryParameters = queryParameters.set('created.lessThan', <any>CreatedLessThan.toISOString());
        }
        if (CreatedSpecified !== undefined && CreatedSpecified !== null) {
            queryParameters = queryParameters.set('created.specified', <any>CreatedSpecified);
        }
        if (IdEquals !== undefined && IdEquals !== null) {
            queryParameters = queryParameters.set('id.equals', <any>IdEquals);
        }
        if (IdGreaterOrEqualThan !== undefined && IdGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('id.greaterOrEqualThan', <any>IdGreaterOrEqualThan);
        }
        if (IdGreaterThan !== undefined && IdGreaterThan !== null) {
            queryParameters = queryParameters.set('id.greaterThan', <any>IdGreaterThan);
        }
        if (IdIn) {
            IdIn.forEach((element) => {
                queryParameters = queryParameters.append('id.in', <any>element);
            })
        }
        if (IdLessOrEqualThan !== undefined && IdLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('id.lessOrEqualThan', <any>IdLessOrEqualThan);
        }
        if (IdLessThan !== undefined && IdLessThan !== null) {
            queryParameters = queryParameters.set('id.lessThan', <any>IdLessThan);
        }
        if (IdSpecified !== undefined && IdSpecified !== null) {
            queryParameters = queryParameters.set('id.specified', <any>IdSpecified);
        }
        if (LastUpdateEquals !== undefined && LastUpdateEquals !== null) {
            queryParameters = queryParameters.set('lastUpdate.equals', <any>LastUpdateEquals.toISOString());
        }
        if (LastUpdateGreaterOrEqualThan !== undefined && LastUpdateGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.greaterOrEqualThan', <any>LastUpdateGreaterOrEqualThan.toISOString());
        }
        if (LastUpdateGreaterThan !== undefined && LastUpdateGreaterThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.greaterThan', <any>LastUpdateGreaterThan.toISOString());
        }
        if (LastUpdateIn0EpochSecond !== undefined && LastUpdateIn0EpochSecond !== null) {
            queryParameters = queryParameters.set('lastUpdate.in[0].epochSecond', <any>LastUpdateIn0EpochSecond);
        }
        if (LastUpdateIn0Nano !== undefined && LastUpdateIn0Nano !== null) {
            queryParameters = queryParameters.set('lastUpdate.in[0].nano', <any>LastUpdateIn0Nano);
        }
        if (LastUpdateLessOrEqualThan !== undefined && LastUpdateLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.lessOrEqualThan', <any>LastUpdateLessOrEqualThan.toISOString());
        }
        if (LastUpdateLessThan !== undefined && LastUpdateLessThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.lessThan', <any>LastUpdateLessThan.toISOString());
        }
        if (LastUpdateSpecified !== undefined && LastUpdateSpecified !== null) {
            queryParameters = queryParameters.set('lastUpdate.specified', <any>LastUpdateSpecified);
        }
        if (LevelEquals !== undefined && LevelEquals !== null) {
            queryParameters = queryParameters.set('level.equals', <any>LevelEquals);
        }
        if (LevelGreaterOrEqualThan !== undefined && LevelGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('level.greaterOrEqualThan', <any>LevelGreaterOrEqualThan);
        }
        if (LevelGreaterThan !== undefined && LevelGreaterThan !== null) {
            queryParameters = queryParameters.set('level.greaterThan', <any>LevelGreaterThan);
        }
        if (LevelIn) {
            LevelIn.forEach((element) => {
                queryParameters = queryParameters.append('level.in', <any>element);
            })
        }
        if (LevelLessOrEqualThan !== undefined && LevelLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('level.lessOrEqualThan', <any>LevelLessOrEqualThan);
        }
        if (LevelLessThan !== undefined && LevelLessThan !== null) {
            queryParameters = queryParameters.set('level.lessThan', <any>LevelLessThan);
        }
        if (LevelSpecified !== undefined && LevelSpecified !== null) {
            queryParameters = queryParameters.set('level.specified', <any>LevelSpecified);
        }
        if (NameContains !== undefined && NameContains !== null) {
            queryParameters = queryParameters.set('name.contains', <any>NameContains);
        }
        if (NameEquals !== undefined && NameEquals !== null) {
            queryParameters = queryParameters.set('name.equals', <any>NameEquals);
        }
        if (NameIn) {
            NameIn.forEach((element) => {
                queryParameters = queryParameters.append('name.in', <any>element);
            })
        }
        if (NameSpecified !== undefined && NameSpecified !== null) {
            queryParameters = queryParameters.set('name.specified', <any>NameSpecified);
        }
        if (Offset !== undefined && Offset !== null) {
            queryParameters = queryParameters.set('offset', <any>Offset);
        }
        if (Page !== undefined && Page !== null) {
            queryParameters = queryParameters.set('page', <any>Page);
        }
        if (PageNumber !== undefined && PageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>PageNumber);
        }
        if (PageSize !== undefined && PageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>PageSize);
        }
        if (Paged !== undefined && Paged !== null) {
            queryParameters = queryParameters.set('paged', <any>Paged);
        }
        if (Size !== undefined && Size !== null) {
            queryParameters = queryParameters.set('size', <any>Size);
        }
        if (Sort) {
            Sort.forEach((element) => {
                queryParameters = queryParameters.append('sort', <any>element);
            })
        }
        if (SortSorted !== undefined && SortSorted !== null) {
            queryParameters = queryParameters.set('sort.sorted', <any>SortSorted);
        }
        if (SortUnsorted !== undefined && SortUnsorted !== null) {
            queryParameters = queryParameters.set('sort.unsorted', <any>SortUnsorted);
        }
        if (Unpaged !== undefined && Unpaged !== null) {
            queryParameters = queryParameters.set('unpaged', <any>Unpaged);
        }
        if (UuidContains !== undefined && UuidContains !== null) {
            queryParameters = queryParameters.set('uuid.contains', <any>UuidContains);
        }
        if (UuidEquals !== undefined && UuidEquals !== null) {
            queryParameters = queryParameters.set('uuid.equals', <any>UuidEquals);
        }
        if (UuidIn) {
            UuidIn.forEach((element) => {
                queryParameters = queryParameters.append('uuid.in', <any>element);
            })
        }
        if (UuidSpecified !== undefined && UuidSpecified !== null) {
            queryParameters = queryParameters.set('uuid.specified', <any>UuidSpecified);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<OrgUnitLevel>>(`${this.basePath}/api/org-unit-levels`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getOrgUnitLevel
     * 
     * @param Id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOrgUnitLevelUsingGET(Id: number, observe?: 'body', reportProgress?: boolean): Observable<OrgUnitLevel>;
    public getOrgUnitLevelUsingGET(Id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OrgUnitLevel>>;
    public getOrgUnitLevelUsingGET(Id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OrgUnitLevel>>;
    public getOrgUnitLevelUsingGET(Id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Id === null || Id === undefined) {
            throw new Error('Required parameter Id was null or undefined when calling getOrgUnitLevelUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<OrgUnitLevel>(`${this.basePath}/api/org-unit-levels/${encodeURIComponent(String(Id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateOrgUnitLevel
     * 
     * @param OrgUnitLevel orgUnitLevel
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateOrgUnitLevelUsingPUT(OrgUnitLevel: OrgUnitLevel, observe?: 'body', reportProgress?: boolean): Observable<OrgUnitLevel>;
    public updateOrgUnitLevelUsingPUT(OrgUnitLevel: OrgUnitLevel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OrgUnitLevel>>;
    public updateOrgUnitLevelUsingPUT(OrgUnitLevel: OrgUnitLevel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OrgUnitLevel>>;
    public updateOrgUnitLevelUsingPUT(OrgUnitLevel: OrgUnitLevel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (OrgUnitLevel === null || OrgUnitLevel === undefined) {
            throw new Error('Required parameter OrgUnitLevel was null or undefined when calling updateOrgUnitLevelUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<OrgUnitLevel>(`${this.basePath}/api/org-unit-levels`,
            OrgUnitLevel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
