/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeValue } from './attributeValue';
import { OrgUnitGroup } from './orgUnitGroup';


export interface OrganisationUnit { 
    Address?: string;
    AttributeValues?: Array<AttributeValue>;
    ClosedDate?: string;
    Code?: string;
    Email?: string;
    Id?: number;
    Latitude?: number;
    Longitude?: number;
    Name: string;
    OpeningDate?: string;
    OrgUnitGroup?: OrgUnitGroup;
    Parent?: OrganisationUnit;
    PhoneNumner?: string;
    Url?: string;
    Uuid?: string;
}
