/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeValue } from './attributeValue';


export interface OrgUnitGroupSet { 
    AttributeValues?: Array<AttributeValue>;
    Code?: string;
    Created?: Date;
    Description?: string;
    Id?: number;
    LastUpdate?: Date;
    Name: string;
    Uuid?: string;
}
