/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserDTO { 
    Activated?: boolean;
    Authorities?: Array<string>;
    CreatedBy?: string;
    CreatedDate?: Date;
    Email?: string;
    FirstName?: string;
    Id?: number;
    ImageUrl?: string;
    LangKey?: string;
    LastModifiedBy?: string;
    LastModifiedDate?: Date;
    LastName?: string;
    Login?: string;
}
