/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OptionSet } from '../model/optionSet';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class OptionSetResourceService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createOptionSet
     * 
     * @param optionSet optionSet
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createOptionSetUsingPOST(optionSet: OptionSet, observe?: 'body', reportProgress?: boolean): Observable<OptionSet>;
    public createOptionSetUsingPOST(optionSet: OptionSet, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OptionSet>>;
    public createOptionSetUsingPOST(optionSet: OptionSet, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OptionSet>>;
    public createOptionSetUsingPOST(optionSet: OptionSet, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (optionSet === null || optionSet === undefined) {
            throw new Error('Required parameter optionSet was null or undefined when calling createOptionSetUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<OptionSet>(`${this.basePath}/api/option-sets`,
            optionSet,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteOptionSet
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteOptionSetUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteOptionSetUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteOptionSetUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteOptionSetUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteOptionSetUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/option-sets/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllOptionSets
     * 
     * @param codeContains 
     * @param codeEquals 
     * @param codeIn 
     * @param codeSpecified 
     * @param createdEquals 
     * @param createdGreaterOrEqualThan 
     * @param createdGreaterThan 
     * @param createdIn0EpochSecond 
     * @param createdIn0Nano 
     * @param createdLessOrEqualThan 
     * @param createdLessThan 
     * @param createdSpecified 
     * @param idEquals 
     * @param idGreaterOrEqualThan 
     * @param idGreaterThan 
     * @param idIn 
     * @param idLessOrEqualThan 
     * @param idLessThan 
     * @param idSpecified 
     * @param lastUpdateEquals 
     * @param lastUpdateGreaterOrEqualThan 
     * @param lastUpdateGreaterThan 
     * @param lastUpdateIn0EpochSecond 
     * @param lastUpdateIn0Nano 
     * @param lastUpdateLessOrEqualThan 
     * @param lastUpdateLessThan 
     * @param lastUpdateSpecified 
     * @param nameContains 
     * @param nameEquals 
     * @param nameIn 
     * @param nameSpecified 
     * @param offset 
     * @param optionValuesIdEquals 
     * @param optionValuesIdGreaterOrEqualThan 
     * @param optionValuesIdGreaterThan 
     * @param optionValuesIdIn 
     * @param optionValuesIdLessOrEqualThan 
     * @param optionValuesIdLessThan 
     * @param optionValuesIdSpecified 
     * @param page Page number of the requested page
     * @param pageNumber 
     * @param pageSize 
     * @param paged 
     * @param size Size of a page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param sortSorted 
     * @param sortUnsorted 
     * @param unpaged 
     * @param uuidContains 
     * @param uuidEquals 
     * @param uuidIn 
     * @param uuidSpecified 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllOptionSetsUsingGET(codeContains?: string, codeEquals?: string, codeIn?: Array<string>, codeSpecified?: boolean, createdEquals?: Date, createdGreaterOrEqualThan?: Date, createdGreaterThan?: Date, createdIn0EpochSecond?: number, createdIn0Nano?: number, createdLessOrEqualThan?: Date, createdLessThan?: Date, createdSpecified?: boolean, idEquals?: number, idGreaterOrEqualThan?: number, idGreaterThan?: number, idIn?: Array<number>, idLessOrEqualThan?: number, idLessThan?: number, idSpecified?: boolean, lastUpdateEquals?: Date, lastUpdateGreaterOrEqualThan?: Date, lastUpdateGreaterThan?: Date, lastUpdateIn0EpochSecond?: number, lastUpdateIn0Nano?: number, lastUpdateLessOrEqualThan?: Date, lastUpdateLessThan?: Date, lastUpdateSpecified?: boolean, nameContains?: string, nameEquals?: string, nameIn?: Array<string>, nameSpecified?: boolean, offset?: number, optionValuesIdEquals?: number, optionValuesIdGreaterOrEqualThan?: number, optionValuesIdGreaterThan?: number, optionValuesIdIn?: Array<number>, optionValuesIdLessOrEqualThan?: number, optionValuesIdLessThan?: number, optionValuesIdSpecified?: boolean, page?: number, pageNumber?: number, pageSize?: number, paged?: boolean, size?: number, sort?: Array<string>, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, uuidContains?: string, uuidEquals?: string, uuidIn?: Array<string>, uuidSpecified?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<OptionSet>>;
    public getAllOptionSetsUsingGET(codeContains?: string, codeEquals?: string, codeIn?: Array<string>, codeSpecified?: boolean, createdEquals?: Date, createdGreaterOrEqualThan?: Date, createdGreaterThan?: Date, createdIn0EpochSecond?: number, createdIn0Nano?: number, createdLessOrEqualThan?: Date, createdLessThan?: Date, createdSpecified?: boolean, idEquals?: number, idGreaterOrEqualThan?: number, idGreaterThan?: number, idIn?: Array<number>, idLessOrEqualThan?: number, idLessThan?: number, idSpecified?: boolean, lastUpdateEquals?: Date, lastUpdateGreaterOrEqualThan?: Date, lastUpdateGreaterThan?: Date, lastUpdateIn0EpochSecond?: number, lastUpdateIn0Nano?: number, lastUpdateLessOrEqualThan?: Date, lastUpdateLessThan?: Date, lastUpdateSpecified?: boolean, nameContains?: string, nameEquals?: string, nameIn?: Array<string>, nameSpecified?: boolean, offset?: number, optionValuesIdEquals?: number, optionValuesIdGreaterOrEqualThan?: number, optionValuesIdGreaterThan?: number, optionValuesIdIn?: Array<number>, optionValuesIdLessOrEqualThan?: number, optionValuesIdLessThan?: number, optionValuesIdSpecified?: boolean, page?: number, pageNumber?: number, pageSize?: number, paged?: boolean, size?: number, sort?: Array<string>, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, uuidContains?: string, uuidEquals?: string, uuidIn?: Array<string>, uuidSpecified?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OptionSet>>>;
    public getAllOptionSetsUsingGET(codeContains?: string, codeEquals?: string, codeIn?: Array<string>, codeSpecified?: boolean, createdEquals?: Date, createdGreaterOrEqualThan?: Date, createdGreaterThan?: Date, createdIn0EpochSecond?: number, createdIn0Nano?: number, createdLessOrEqualThan?: Date, createdLessThan?: Date, createdSpecified?: boolean, idEquals?: number, idGreaterOrEqualThan?: number, idGreaterThan?: number, idIn?: Array<number>, idLessOrEqualThan?: number, idLessThan?: number, idSpecified?: boolean, lastUpdateEquals?: Date, lastUpdateGreaterOrEqualThan?: Date, lastUpdateGreaterThan?: Date, lastUpdateIn0EpochSecond?: number, lastUpdateIn0Nano?: number, lastUpdateLessOrEqualThan?: Date, lastUpdateLessThan?: Date, lastUpdateSpecified?: boolean, nameContains?: string, nameEquals?: string, nameIn?: Array<string>, nameSpecified?: boolean, offset?: number, optionValuesIdEquals?: number, optionValuesIdGreaterOrEqualThan?: number, optionValuesIdGreaterThan?: number, optionValuesIdIn?: Array<number>, optionValuesIdLessOrEqualThan?: number, optionValuesIdLessThan?: number, optionValuesIdSpecified?: boolean, page?: number, pageNumber?: number, pageSize?: number, paged?: boolean, size?: number, sort?: Array<string>, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, uuidContains?: string, uuidEquals?: string, uuidIn?: Array<string>, uuidSpecified?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OptionSet>>>;
    public getAllOptionSetsUsingGET(codeContains?: string, codeEquals?: string, codeIn?: Array<string>, codeSpecified?: boolean, createdEquals?: Date, createdGreaterOrEqualThan?: Date, createdGreaterThan?: Date, createdIn0EpochSecond?: number, createdIn0Nano?: number, createdLessOrEqualThan?: Date, createdLessThan?: Date, createdSpecified?: boolean, idEquals?: number, idGreaterOrEqualThan?: number, idGreaterThan?: number, idIn?: Array<number>, idLessOrEqualThan?: number, idLessThan?: number, idSpecified?: boolean, lastUpdateEquals?: Date, lastUpdateGreaterOrEqualThan?: Date, lastUpdateGreaterThan?: Date, lastUpdateIn0EpochSecond?: number, lastUpdateIn0Nano?: number, lastUpdateLessOrEqualThan?: Date, lastUpdateLessThan?: Date, lastUpdateSpecified?: boolean, nameContains?: string, nameEquals?: string, nameIn?: Array<string>, nameSpecified?: boolean, offset?: number, optionValuesIdEquals?: number, optionValuesIdGreaterOrEqualThan?: number, optionValuesIdGreaterThan?: number, optionValuesIdIn?: Array<number>, optionValuesIdLessOrEqualThan?: number, optionValuesIdLessThan?: number, optionValuesIdSpecified?: boolean, page?: number, pageNumber?: number, pageSize?: number, paged?: boolean, size?: number, sort?: Array<string>, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, uuidContains?: string, uuidEquals?: string, uuidIn?: Array<string>, uuidSpecified?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





















































        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codeContains !== undefined && codeContains !== null) {
            queryParameters = queryParameters.set('code.contains', <any>codeContains);
        }
        if (codeEquals !== undefined && codeEquals !== null) {
            queryParameters = queryParameters.set('code.equals', <any>codeEquals);
        }
        if (codeIn) {
            codeIn.forEach((element) => {
                queryParameters = queryParameters.append('code.in', <any>element);
            })
        }
        if (codeSpecified !== undefined && codeSpecified !== null) {
            queryParameters = queryParameters.set('code.specified', <any>codeSpecified);
        }
        if (createdEquals !== undefined && createdEquals !== null) {
            queryParameters = queryParameters.set('created.equals', <any>createdEquals.toISOString());
        }
        if (createdGreaterOrEqualThan !== undefined && createdGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('created.greaterOrEqualThan', <any>createdGreaterOrEqualThan.toISOString());
        }
        if (createdGreaterThan !== undefined && createdGreaterThan !== null) {
            queryParameters = queryParameters.set('created.greaterThan', <any>createdGreaterThan.toISOString());
        }
        if (createdIn0EpochSecond !== undefined && createdIn0EpochSecond !== null) {
            queryParameters = queryParameters.set('created.in[0].epochSecond', <any>createdIn0EpochSecond);
        }
        if (createdIn0Nano !== undefined && createdIn0Nano !== null) {
            queryParameters = queryParameters.set('created.in[0].nano', <any>createdIn0Nano);
        }
        if (createdLessOrEqualThan !== undefined && createdLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('created.lessOrEqualThan', <any>createdLessOrEqualThan.toISOString());
        }
        if (createdLessThan !== undefined && createdLessThan !== null) {
            queryParameters = queryParameters.set('created.lessThan', <any>createdLessThan.toISOString());
        }
        if (createdSpecified !== undefined && createdSpecified !== null) {
            queryParameters = queryParameters.set('created.specified', <any>createdSpecified);
        }
        if (idEquals !== undefined && idEquals !== null) {
            queryParameters = queryParameters.set('id.equals', <any>idEquals);
        }
        if (idGreaterOrEqualThan !== undefined && idGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('id.greaterOrEqualThan', <any>idGreaterOrEqualThan);
        }
        if (idGreaterThan !== undefined && idGreaterThan !== null) {
            queryParameters = queryParameters.set('id.greaterThan', <any>idGreaterThan);
        }
        if (idIn) {
            idIn.forEach((element) => {
                queryParameters = queryParameters.append('id.in', <any>element);
            })
        }
        if (idLessOrEqualThan !== undefined && idLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('id.lessOrEqualThan', <any>idLessOrEqualThan);
        }
        if (idLessThan !== undefined && idLessThan !== null) {
            queryParameters = queryParameters.set('id.lessThan', <any>idLessThan);
        }
        if (idSpecified !== undefined && idSpecified !== null) {
            queryParameters = queryParameters.set('id.specified', <any>idSpecified);
        }
        if (lastUpdateEquals !== undefined && lastUpdateEquals !== null) {
            queryParameters = queryParameters.set('lastUpdate.equals', <any>lastUpdateEquals.toISOString());
        }
        if (lastUpdateGreaterOrEqualThan !== undefined && lastUpdateGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.greaterOrEqualThan', <any>lastUpdateGreaterOrEqualThan.toISOString());
        }
        if (lastUpdateGreaterThan !== undefined && lastUpdateGreaterThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.greaterThan', <any>lastUpdateGreaterThan.toISOString());
        }
        if (lastUpdateIn0EpochSecond !== undefined && lastUpdateIn0EpochSecond !== null) {
            queryParameters = queryParameters.set('lastUpdate.in[0].epochSecond', <any>lastUpdateIn0EpochSecond);
        }
        if (lastUpdateIn0Nano !== undefined && lastUpdateIn0Nano !== null) {
            queryParameters = queryParameters.set('lastUpdate.in[0].nano', <any>lastUpdateIn0Nano);
        }
        if (lastUpdateLessOrEqualThan !== undefined && lastUpdateLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.lessOrEqualThan', <any>lastUpdateLessOrEqualThan.toISOString());
        }
        if (lastUpdateLessThan !== undefined && lastUpdateLessThan !== null) {
            queryParameters = queryParameters.set('lastUpdate.lessThan', <any>lastUpdateLessThan.toISOString());
        }
        if (lastUpdateSpecified !== undefined && lastUpdateSpecified !== null) {
            queryParameters = queryParameters.set('lastUpdate.specified', <any>lastUpdateSpecified);
        }
        if (nameContains !== undefined && nameContains !== null) {
            queryParameters = queryParameters.set('name.contains', <any>nameContains);
        }
        if (nameEquals !== undefined && nameEquals !== null) {
            queryParameters = queryParameters.set('name.equals', <any>nameEquals);
        }
        if (nameIn) {
            nameIn.forEach((element) => {
                queryParameters = queryParameters.append('name.in', <any>element);
            })
        }
        if (nameSpecified !== undefined && nameSpecified !== null) {
            queryParameters = queryParameters.set('name.specified', <any>nameSpecified);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (optionValuesIdEquals !== undefined && optionValuesIdEquals !== null) {
            queryParameters = queryParameters.set('optionValuesId.equals', <any>optionValuesIdEquals);
        }
        if (optionValuesIdGreaterOrEqualThan !== undefined && optionValuesIdGreaterOrEqualThan !== null) {
            queryParameters = queryParameters.set('optionValuesId.greaterOrEqualThan', <any>optionValuesIdGreaterOrEqualThan);
        }
        if (optionValuesIdGreaterThan !== undefined && optionValuesIdGreaterThan !== null) {
            queryParameters = queryParameters.set('optionValuesId.greaterThan', <any>optionValuesIdGreaterThan);
        }
        if (optionValuesIdIn) {
            optionValuesIdIn.forEach((element) => {
                queryParameters = queryParameters.append('optionValuesId.in', <any>element);
            })
        }
        if (optionValuesIdLessOrEqualThan !== undefined && optionValuesIdLessOrEqualThan !== null) {
            queryParameters = queryParameters.set('optionValuesId.lessOrEqualThan', <any>optionValuesIdLessOrEqualThan);
        }
        if (optionValuesIdLessThan !== undefined && optionValuesIdLessThan !== null) {
            queryParameters = queryParameters.set('optionValuesId.lessThan', <any>optionValuesIdLessThan);
        }
        if (optionValuesIdSpecified !== undefined && optionValuesIdSpecified !== null) {
            queryParameters = queryParameters.set('optionValuesId.specified', <any>optionValuesIdSpecified);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (paged !== undefined && paged !== null) {
            queryParameters = queryParameters.set('paged', <any>paged);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (sort) {
            sort.forEach((element) => {
                queryParameters = queryParameters.append('sort', <any>element);
            })
        }
        if (sortSorted !== undefined && sortSorted !== null) {
            queryParameters = queryParameters.set('sort.sorted', <any>sortSorted);
        }
        if (sortUnsorted !== undefined && sortUnsorted !== null) {
            queryParameters = queryParameters.set('sort.unsorted', <any>sortUnsorted);
        }
        if (unpaged !== undefined && unpaged !== null) {
            queryParameters = queryParameters.set('unpaged', <any>unpaged);
        }
        if (uuidContains !== undefined && uuidContains !== null) {
            queryParameters = queryParameters.set('uuid.contains', <any>uuidContains);
        }
        if (uuidEquals !== undefined && uuidEquals !== null) {
            queryParameters = queryParameters.set('uuid.equals', <any>uuidEquals);
        }
        if (uuidIn) {
            uuidIn.forEach((element) => {
                queryParameters = queryParameters.append('uuid.in', <any>element);
            })
        }
        if (uuidSpecified !== undefined && uuidSpecified !== null) {
            queryParameters = queryParameters.set('uuid.specified', <any>uuidSpecified);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<OptionSet>>(`${this.basePath}/api/option-sets`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getOptionSet
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOptionSetUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<OptionSet>;
    public getOptionSetUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OptionSet>>;
    public getOptionSetUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OptionSet>>;
    public getOptionSetUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getOptionSetUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<OptionSet>(`${this.basePath}/api/option-sets/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateOptionSet
     * 
     * @param optionSet optionSet
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateOptionSetUsingPUT(optionSet: OptionSet, observe?: 'body', reportProgress?: boolean): Observable<OptionSet>;
    public updateOptionSetUsingPUT(optionSet: OptionSet, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OptionSet>>;
    public updateOptionSetUsingPUT(optionSet: OptionSet, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OptionSet>>;
    public updateOptionSetUsingPUT(optionSet: OptionSet, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (optionSet === null || optionSet === undefined) {
            throw new Error('Required parameter optionSet was null or undefined when calling updateOptionSetUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<OptionSet>(`${this.basePath}/api/option-sets`,
            optionSet,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
