/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OptionSet } from './optionSet';


export interface Attribute { 
    code?: string;
    id?: number;
    mandatory: boolean;
    name: string;
    optionSet?: OptionSet;
    orgUnitAttribute?: boolean;
    orgUnitGroupAttribute?: boolean;
    orgUnitGroupSetAttribute?: boolean;
    sortOrder?: number;
    userAttribute?: boolean;
    uuid?: string;
    valueType: string;
}
