/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeValue } from './attributeValue';
import { OrgUnitGroup } from './orgUnitGroup';


export interface OrganisationUnit { 
    address?: string;
    attributeValues?: Array<AttributeValue>;
    closedDate?: string;
    code?: string;
    email?: string;
    id?: number;
    latitude?: number;
    longitude?: number;
    name: string;
    openingDate?: string;
    orgUnitGroup?: OrgUnitGroup;
    parent?: OrganisationUnit;
    phoneNumner?: string;
    url?: string;
    uuid?: string;
}
