/**
 * server API
 * server API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeValue } from './attributeValue';
import { OrgUnitGroupSet } from './orgUnitGroupSet';


export interface OrgUnitGroup { 
    attributeValues?: Array<AttributeValue>;
    code?: string;
    created?: Date;
    id?: number;
    lastUpdate?: Date;
    name: string;
    orgUnitGroupSet: OrgUnitGroupSet;
    uid?: string;
}
